import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    img: "https://sahudigital.vercel.app/images/product-img/apple-iphone-13-pro.jpg",
    name: "iPhone 13 Pro",
    brand: "Apple Inc.",
    price: 112900,
    originalPrice: 119900,
    isBestSeller: true,
    category: "Apple",
    rating: 4.8,
  },
  {
    _id: uuid(),
    img: "https://sahudigital.vercel.app/images/product-img/samsung-galaxy-s22-ultra.jpg",
    name: "Galaxy S22 Ultra",
    brand: "Samsung Electronics",
    price: 90950,
    originalPrice: 131999,
    isBestSeller: false,
    category: "Samsung",
    rating: 4.2,
  },
  {
    _id: uuid(),
    img: "https://sahudigital.vercel.app/images/product-img/oneplus-10-pro.jpg",
    name: "OnePlus 10 Pro",
    brand: "OnePlus Technology Co.",
    price: 60999,
    originalPrice: 66299,
    isBestSeller: true,
    category: "One Plus",
    rating: 4.5,
  },
  {
    _id: uuid(),
    img: "https://sahudigital.vercel.app/images/product-img/realme-gt-2.jpg",
    name: "Realme GT 2",
    brand: "Realme Mobile Ltd.",
    price: 34999,
    originalPrice: 39299,
    isBestSeller: false,
    category: "Realme",
    rating: 4.0,
  },
  {
    _id: uuid(),
    img: "https://sahudigital.vercel.app/images/product-img/apple-iphone-13-pro-max.jpg",
    name: "iPhone 13 Pro Max",
    brand: "Apple Inc.",
    price: 122900,
    originalPrice: 129900,
    isBestSeller: false,
    category: "Apple",
    rating: 3.8,
  },
  {
    _id: uuid(),
    img: "https://sahudigital.vercel.app/images/product-img/samsung-galaxy-s22-plus.jpg",
    name: "Galaxy S22 Plus",
    brand: "Samsung Electronics",
    price: 78999,
    originalPrice: 101999,
    isBestSeller: false,
    category: "Samsung",
    rating: 3.2,
  },
  {
    _id: uuid(),
    img: "https://sahudigital.vercel.app/images/product-img/oneplus-10-r.jpg",
    name: "OnePlus 10R",
    brand: "OnePlus Technology Co.",
    price: 35999,
    originalPrice: 38299,
    isBestSeller: true,
    category: "One Plus",
    rating: 3.0,
  },
  {
    _id: uuid(),
    img: "https://sahudigital.vercel.app/images/product-img/realme-gt-neo-3.jpg",
    name: "Realme GT Neo 3",
    brand: "Realme Mobile Ltd.",
    price: 35999,
    originalPrice: 39999,
    isBestSeller: false,
    category: "Realme",
    rating: 3.5,
  },
  {
    _id: uuid(),
    img: "https://sahudigital.vercel.app/images/product-img/apple-iphone-13.jpg",
    name: "iPhone 13",
    brand: "Apple Inc.",
    price: 69900,
    originalPrice: 79900,
    isBestSeller: false,
    category: "Apple",
    rating: 3.8,
  },
  {
    _id: uuid(),
    img: "https://sahudigital.vercel.app/images/product-img/samsung-galaxy-s22.jpg",
    name: "Galaxy S22",
    brand: "Samsung Electronics",
    price: 62000,
    originalPrice: 85999,
    isBestSeller: false,
    category: "Samsung",
    rating: 3.2,
  },
  {
    _id: uuid(),
    img: "https://sahudigital.vercel.app/images/product-img/oneplus-nord-2t.jpg",
    name: "OnePlus Nord 2T",
    brand: "OnePlus Technology Co.",
    price: 27999,
    originalPrice: 28999,
    isBestSeller: false,
    category: "One Plus",
    rating: 3.5,
  },
  {
    _id: uuid(),
    img: "https://sahudigital.vercel.app/images/product-img/realme-gt-neo-2.jpg",
    name: "Realme GT Neo 2",
    brand: "Realme Mobile Ltd.",
    price: 31999,
    originalPrice: 34299,
    isBestSeller: false,
    category: "Realme",
    rating: 3.0,
  },
  {
    _id: uuid(),
    img: "https://sahudigital.vercel.app/images/product-img/apple-iphone-13-mini.jpg",
    name: "iPhone 13 Mini",
    brand: "Apple Inc.",
    price: 68990,
    originalPrice: 69900,
    isBestSeller: false,
    category: "Apple",
    rating: 2.8,
  },
  {
    _id: uuid(),
    img: "https://sahudigital.vercel.app/images/product-img/samsung-galaxy-s21-fe.jpg",
    name: "Galaxy S21 FE",
    brand: "Samsung Electronics",
    price: 49999,
    originalPrice: 74999,
    isBestSeller: false,
    category: "Samsung",
    rating: 2.2,
  },
  {
    _id: uuid(),
    img: "https://sahudigital.vercel.app/images/product-img/oneplus-nord-ce2.jpg",
    name: "OnePlus Nord CE 2",
    brand: "OnePlus Technology Co.",
    price: 24999,
    originalPrice: 23999,
    isBestSeller: false,
    category: "One Plus",
    rating: 2.5,
  },
  {
    _id: uuid(),
    img: "https://sahudigital.vercel.app/images/product-img/realme-9-pro-plus.jpg",
    name: "Realme 9 Pro Plus",
    brand: "Realme Mobile Ltd.",
    price: 24990,
    originalPrice: 29299,
    isBestSeller: false,
    category: "Realme",
    rating: 2.0,
  }  
];
